apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmap-booking.yaml
- configmap-catalog.yaml
- configmap-notification.yaml
- booking-service.yaml
- catalog-service.yaml
- notification-service.yaml
- load-balancers.yaml
images:
- name: booking-service
  newName: acrapugupta.azurecr.io/booking-service
  newTag: latest
- name: catalog-service
  newName: acrapugupta.azurecr.io/catalog-service
  newTag: latest
- name: notification-service
  newName: acrapugupta.azurecr.io/notification-service
  newTag: latest
