apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap-booking.yaml
  - configmap-catalog.yaml
  - configmap-notification.yaml
  - booking-service.yaml
  - catalog-service.yaml
  - notification-service.yaml
  - ingress.yaml
